# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  cd-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Fetch tags
        run: git fetch --tags origin

      - name: Setup transcrypt
        shell: bash
        env:
          TRANSCRYPT_PASSWORD: ${{ secrets.TRANSCRYPT_PASSWORD }}
        run: |
          git clone -b v2.1.0 https://github.com/elasticdog/transcrypt.git transcrypt
          git reset --hard
          git clean -df
          ./transcrypt/transcrypt -c aes-256-cbc -p "$TRANSCRYPT_PASSWORD" -y

      # Setup jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Deploy to appcenter
        run: bundle exec fastlane distribute --env staging
