# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "**" ]
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Setup jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      # Runs a single command using the runners shell
      - name: Execute unit tests
        run: gradle runUnitTests

      - name: Unit tests results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: |
            feature/featureMain/build/reports/tests/testDebugUnitTest/*
            library/libContact/build/reports/tests/testDebugUnitTest/*
